# 原神模拟十连设置
default:
  # 每日抽卡数
  count: 10
  # 百连是否占用10次抽卡次数 1-是 0-不是
  tenGacha: 1
  # 撤回消息 0-120 秒, 0不撤回
  delMsg: 110
  # 角色池，武器池限制次数分开计算  1-分开 0-不分开
  LimitSeparate: 0

# 群单独设置
123465:
  count: 10
  # 撤回消息 0-120 秒, 0不撤回
  delMsg: 110
  # 角色池，武器池限制次数分开计算  1-分开 0-不分开
  LimitSeparate: 0
